### ISSUE TITLE
ThemeForest checklist for launch

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#93]
- [x] .gitmodules .travis.yml .gitignore Hidden Files or Folders found.
- [x] Please remove any extraneous directories like .git or .svn from the ZIP file before uploading it.
- [x] screen_icon() found in the file framework/includes/admin/edd-license.php. Deprecated since version 3.8.
- [x] please fix php notices - http://envato.d.pr/5wip/mzmdfoor
- [x] the visual editor styling required improvements and there is an odd grey background - http://envato.d.pr/1gq39/3fGlIfaz
- [x] Make sure all the WP default widgets display properly in all widgetized areas. You can check with monster widgets plugin. http://envato.d.pr/1bTOK/q90SxvoI - http://envato.d.pr/1lbiM/2ZwCruoI - http://envato.d.pr/12qdA/eI2OoFBK
- [x] styling is gone when I choose to use my own colors - http://envato.d.pr/TChj/dzrqQ5l5
- [x] the header image appears before the site name/logo - http://envato.d.pr/12nSg/GhkEV2MF - which is odd.
- [x] there is no spacing between page title and header - http://envato.d.pr/1aYRv/r56CfpLN
- [x] Data Validation issues have been found in your theme. All dynamic data must be correctly escaped for the context where it is rendered.

- All dynamic data must be escaped with esc_attr() before rendered in an html attribute.
- Whenever you are rendering a url to the screen its value must be passed through esc_url() first.
- If dynamic data is rendered inside an attribute that triggers a JavaScript event, it must be escaped with esc_js().

http://codex.wordpress.org/Data_Validation http://developer.wordpress.com/themes/escaping/ http://code.tutsplus.com/articles/data-sanitization-and-validation-with-wordpress--wp-25536

eg: http://envato.d.pr/16GZI/1tD8akiv and more
- [ ] footer text doesn't work - http://envato.d.pr/Q4WH/3KHDNGxy - front end - http://envato.d.pr/cnd0/nc0OTuiF

**Comment by angela-crist** [comment]
@chriswallace Please update the above list of what was included in the most recent version you submitted to ThemeForest
